### ISSUE TITLE
Smash Bros .app Files are unable to install.

### ISSUE THREAD

**Issue by CaptainCoward** [wiiu-env/wudd#22]
I have used Wudd for a lot of my CDs without having any issues. However Smash doesn't seem to be able to install (to USB) and will always stop at about 47%  (using Wupinstaller GX2) when dumping as .app files. The biggest difference between other games seem that the app files of Smash are getting pretty big (up to 3.9GB). So i investigated this "issue" further and found out that the two .h3 files of the biggest two .app files differ in size when downloading from the Nus Servers

For example the biggest files are 00000017.app and 00000018.app. While both files i dumped with wudd are similar to the ones i downloaded from the NUS servers their h3 files are not, they differ in size. As you can see on my screenshot. The  00000017.h3 and 00000018.h3  WUDD created are both 64bytes, while the ones i downloade from NUS are 320bytes.
![Screenshot 2023-01-02 161647](https://user-images.githubusercontent.com/15695543/210250727-74deec0e-c0cf-4f45-8b94-a7e98425dd10.png)

any clue what's the reason?

**Comment by Maschell** [comment]
Thanks for this detailed report, this would also explain the issues other people have. I'll look into it!

**Comment by CaptainCoward** [comment]
No problem. Glad if i can help. Btw i just replaced the two h3 files with the files i got from NUS and installation went fine.

**Comment by Maschell** [comment]
Found the issue! The size of the h3 was stored in a uint8_t which is too small to hold the correct size for some files =(

Should be fixed with https://github.com/wiiu-env/wudd/commit/2b46671df60846c907191a7eae4946402a0e9a59
A nightly can be downloaded here: https://github.com/wiiu-env/wudd/releases/tag/wudd-20230102-161642
