### ISSUE TITLE
[BUG] Exiting from the exit option infinite loops on wii u menu loading

### ISSUE THREAD

**Issue by Xpl0itU** [wiiu-env/wudd#5]
When picking exit from the main menu, it gets stuck on loading the wii u menu, the music plays, but never reaches the menu

Environment:
- Version: 5.5.5E
- CFW: Tiramisu, latest MochaPayload
- Launching from HBL on Mii Maker

**Comment by Maschell** [comment]
Fixed with https://github.com/wiiu-env/wudd/commit/90b6a36addeb1d4ca3f1a7fa1dce53c3732b1042
