### ISSUE TITLE
FR: Dump Wii discs too

### ISSUE THREAD

**Issue by JohnVeness** [wiiu-env/wudd#8]
Hello. Many thanks for this tool. I wonder - would it be possible to make it dump Wii discs too? I'm aware of CleanRip, but it would be nice to have one tool do both discs!

**Comment by Maschell** [comment]
Currently there is now known way to read Wii Discs from Wii U mode

**Comment by JohnVeness** [comment]
Ah, OK. Thanks for the quick reply :)
